/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVaultRouteImport } from './routes/app.vault'
import { Route as AppTrajectoryRouteImport } from './routes/app.trajectory'
import { Route as AppSpendingRouteImport } from './routes/app.spending'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRetirementRouteImport } from './routes/app.retirement'
import { Route as AppRecommendedRouteImport } from './routes/app.recommended'
import { Route as AppQuestsRouteImport } from './routes/app.quests'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppGuardrailsRouteImport } from './routes/app.guardrails'
import { Route as AppCoachRouteImport } from './routes/app.coach'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppTrajectoryRoute = AppTrajectoryRouteImport.update({
  id: '/trajectory',
  path: '/trajectory',
  getParentRoute: () => AppRoute,
} as any)
const AppSpendingRoute = AppSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRetirementRoute = AppRetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendedRoute = AppRecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppGuardrailsRoute = AppGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/coach': typeof AppCoachRoute
  '/app/guardrails': typeof AppGuardrailsRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quests': typeof AppQuestsRoute
  '/app/recommended': typeof AppRecommendedRoute
  '/app/retirement': typeof AppRetirementRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/trajectory': typeof AppTrajectoryRoute
  '/app/vault': typeof AppVaultRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/coach': typeof AppCoachRoute
  '/app/guardrails': typeof AppGuardrailsRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quests': typeof AppQuestsRoute
  '/app/recommended': typeof AppRecommendedRoute
  '/app/retirement': typeof AppRetirementRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/trajectory': typeof AppTrajectoryRoute
  '/app/vault': typeof AppVaultRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/coach': typeof AppCoachRoute
  '/app/guardrails': typeof AppGuardrailsRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quests': typeof AppQuestsRoute
  '/app/recommended': typeof AppRecommendedRoute
  '/app/retirement': typeof AppRetirementRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spending': typeof AppSpendingRoute
  '/app/trajectory': typeof AppTrajectoryRoute
  '/app/vault': typeof AppVaultRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/coach'
    | '/app/guardrails'
    | '/app/progress'
    | '/app/quests'
    | '/app/recommended'
    | '/app/retirement'
    | '/app/settings'
    | '/app/spending'
    | '/app/trajectory'
    | '/app/vault'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/coach'
    | '/app/guardrails'
    | '/app/progress'
    | '/app/quests'
    | '/app/recommended'
    | '/app/retirement'
    | '/app/settings'
    | '/app/spending'
    | '/app/trajectory'
    | '/app/vault'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/coach'
    | '/app/guardrails'
    | '/app/progress'
    | '/app/quests'
    | '/app/recommended'
    | '/app/retirement'
    | '/app/settings'
    | '/app/spending'
    | '/app/trajectory'
    | '/app/vault'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vault': {
      id: '/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trajectory': {
      id: '/app/trajectory'
      path: '/trajectory'
      fullPath: '/app/trajectory'
      preLoaderRoute: typeof AppTrajectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spending': {
      id: '/app/spending'
      path: '/spending'
      fullPath: '/app/spending'
      preLoaderRoute: typeof AppSpendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/retirement': {
      id: '/app/retirement'
      path: '/retirement'
      fullPath: '/app/retirement'
      preLoaderRoute: typeof AppRetirementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommended': {
      id: '/app/recommended'
      path: '/recommended'
      fullPath: '/app/recommended'
      preLoaderRoute: typeof AppRecommendedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quests': {
      id: '/app/quests'
      path: '/quests'
      fullPath: '/app/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guardrails': {
      id: '/app/guardrails'
      path: '/guardrails'
      fullPath: '/app/guardrails'
      preLoaderRoute: typeof AppGuardrailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppGuardrailsRoute: typeof AppGuardrailsRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuestsRoute: typeof AppQuestsRoute
  AppRecommendedRoute: typeof AppRecommendedRoute
  AppRetirementRoute: typeof AppRetirementRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpendingRoute: typeof AppSpendingRoute
  AppTrajectoryRoute: typeof AppTrajectoryRoute
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppGuardrailsRoute: AppGuardrailsRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuestsRoute: AppQuestsRoute,
  AppRecommendedRoute: AppRecommendedRoute,
  AppRetirementRoute: AppRetirementRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpendingRoute: AppSpendingRoute,
  AppTrajectoryRoute: AppTrajectoryRoute,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
